#!/usr/bin/env bash

set -e

cwd="$(pwd)"

makelink() {
  target="$cwd/dot/$1"
  linkname="$HOME/$2"

  # Check if target exists
  if [[ -e "$linkname" ]]; then
    # Check if already linked
    if [[ "$(readlink -f "$target")" == "$(readlink -f "$linkname")" ]]; then
      return 0
    fi

    newname="$linkname-$(date +%s)"
    mv "$linkname" "$newname"
    echo "Warn: target exists, renamed to $newname"
  fi

  mkdir -p "$(dirname "$linkname")"
  ln -sv "$target" "$linkname"
}

# General
makelink tmux.conf .tmux.conf
makelink gitconfig .gitconfig
makelink zshrc     .zshrc
makelink antigen   .config/antigen
makelink nvim      .config/nvim
makelink kitty     .config/kitty

# Desktop
makelink xinitrc   .xinitrc
makelink dunst     .config/dunst
makelink i3        .config/i3
makelink i3status  .config/i3status
makelink polybar   .config/polybar
makelink rofi      .config/rofi
makelink picom     .config/picom

makelink gtk-settings.ini .config/gtk-3.0/settings.ini

makelink i3status/checkupdates.service .config/systemd/user/checkupdates.service
makelink i3status/checkupdates.timer   .config/systemd/user/checkupdates.timer
systemctl --user enable checkupdates.timer

# Other apps
makelink plover .config/plover

echo 'Done'
