#!/bin/sh
# Settings
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="brave"

if [ -d "$HOME/.local/bin" ] ; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# Set up SSH
export SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh

# Autostart X if logged in on tty1
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  sleep 1
  startx
fi
