#!/bin/sh

hostname=$(hostnamectl hostname)

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# monitor configuration
layout() {
#  # If using xf86-video-intel
#  xrandr \
#    --output eDP1 \
#      --mode 1920x1080 \
#      --pos 0x0 \
#      --rotate normal \
#    --output DP1 \
#      --primary \
#      --mode 1920x1080 \
#      --pos 1920x0 \
#      --rotate normal \
#      --set "Broadcast RGB" "Full" \
#    --output VIRTUAL1 \
#      --off

  # Not using xf86-video-intel
  xrandr \
    --output eDP-1 \
      --mode 1920x1080 \
      --pos 0x0 \
      --rotate normal \
    --output DP-1 \
      --primary \
      --mode 1920x1080 \
      --pos 1920x0 \
      --rotate normal \
      --set "Broadcast RGB" "Full"
}

if [[ "$hostname" == "hoshizora" ]]; then
  until layout; do :; done
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# start i3
exec i3
