#!/bin/sh

# remap escape and caps
setxkbmap -option caps:escape
# keyboard repeat rate
xset r rate 200 25
# touchpad natural scrolling
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1

exec i3
