#!/bin/sh

# monitor configuration
layout() {
  xrandr \
    --output eDP1 \
      --mode 1920x1080 \
      --pos 0x0 \
      --rotate normal \
    --output DP1 \
      --primary \
      --mode 1920x1080 \
      --pos 1920x0 \
      --rotate normal \
      --set "Broadcast RGB" "Full" \
    --output VIRTUAL1 \
      --off
}

until layout; do :; done

# Start i3
i3
