export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# Fuzzy completion
CASE_SENSITIVE=false
HYPHEN_INSENSITIVE=true

# Automatically update without prompting
DISABLE_UPDATE_PROMPT=true
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Add ~/.local/bin to path
typeset -U path # make path unique
path[1,0]=~/.local/bin

# Aliases
alias t="tmux"
alias k="kubectl"
alias gpoh="git push -u origin HEAD"
alias clip="xclip -selection clipboard"

# fix kitty ssh
alias ssh="TERM=xterm-256color ssh"

# vim
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

# global config
export EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="kitty"

# ssh gpg agent
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye >/dev/null

# direnv hook
command -v direnv &>/dev/null && eval "$(direnv hook zsh)"
